### ISSUE TITLE
AEFI Form report date constraint

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#113]
Report adverse event: This form allows selection of AEFI start date outside the immunisation date of the selected vaccine which obviously breaks the causation logic.

- [x] Add constraints to the form to have the date picker only allow earliest date to be the date of the selected Vaccine.

**Comment by ekigamba** [comment]
It seems that the form is already intelligent and prefills the date that the vaccine was done next to the vaccine name on the vaccine question.

To enable this we will have to create a new hidden field which maps the vaccine selected to a date. This field will then provide the min date value for the *date of causation*. However, from the   **deceased report form** it seems that this might do validation a bit late or not work as we would want it. I am not sure if rules can be used here to or we can use the `min_causation_date` field-value directly in the **date selector's min_date** field.

We can test the first solution which would take little effort, if that does not work, the we would try the other solutions starting from what we already have and last result would be to edit the widget so that it can pick the min values from another field

**Comment by hmakandi** [comment]
Completed and closing
