### ISSUE TITLE
Child Health Investigate Vaccine naming issue

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#131]
- [ ] Suddenly the labels for vaccination groups changed to variable names as below
![Screenshot_1570524155](https://user-images.githubusercontent.com/18394882/66818275-c2b5ff80-ef45-11e9-8f39-b7d019901475.png)

**Comment by ekigamba** [comment]
This bug is present in `org.smartregister:opensrp-client-child:0.1.10-SNAPSHOT` where it can be fixed by adding 5 months, 6 months, 7 months, 15 months & 22 months translations to the `strings.xml` as `five_months`.

This is fixed in `org.smartregister:opensrp-client-child:0.1.11-SNAPSHOT` and does not require any code change

**Comment by hmakandi** [comment]
Confirmed as fixed
