### ISSUE TITLE
ANC workflow and previous visits issues

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#289]
1. ANC is designed to cater for women from their first contact and is not designed to capture previous visits. Malawi is requesting to capture the visit at which the woman is being recorded in the system, such that if she is in her 4th Visit, the system should be able to record this. Problems that arise due to this requirement is that the scheduling happens based on the woman's GA, and thus it would calculate the schedule based off this and not the visit number. 

- Option given is to record the previous visits during the registration process, change the global counter for the contact visit, and reflect the new counter in the contact schedule. Downside of this is that should the woman have the subsequent visit in another health facility and come back for the next one, we would not be able to increment the contact again.

-  It would probably be better to drop the contact numbers all together, and have a field reflect the number of visits in the profile.

2. ANC only allows 1 person to cater for the client's contact through out. Malawi has a problem here as there are 4 people involved during the contact process and the idea is to sync the information in order to distribute this work load. Currently ANC does not sync a contact that is in progress. There will be a different health worker addressing registration(this ok for sync), another for tests, another for counselling and another for the other containers(profile,S&F,P&E). 
Options here are: 

- **Sync the event on each container and not to allow edits.** This option is possible as each container is synced as its own event. On submit, it can be that each container is locked and sync, and since it is tagged as a complete event, it would not support edit. To support edit in this option, the update events would be needed.

- **Introduce draft events and sync them across the devices.** This brings about complexities when introducing edits, as each draft event is editable and thus would cause data inconsistency and overwriting in case multiple edits are supported. It would also bring about audit issues when we cannot account on which action was performed by each user. Solution proposed is to allow the originator to sync the data, as it would prevent the overhead of dealing with data loss and maintain audit trail when the event is posted as a complete event. 

- **Introduce update events such that there is no need for draft events.** This would allowing anybody with access to edit and would thus need changing ANC to accommodate update events. This would maintain data integrity and audit trail, though would introduce development overheads as each update event would need to be processed by the app. 

- **Tasking:** Have each action as an event based on a plan. When each task is marked completed, it can then progress in a pre-determined order that is easily customisable according to the ANC plan.The potential issue comes in when there is an edit on a task, as each task goes through various statuses and then are completed.

**Comment by rowo** [comment]
@hmakandi 

@mberg and I quickly chatted, though he was a little tired. Conclusions were:

1. ANC contact numbers - no real strong opinion here. Having it follow PNC model would be okay if MOH and WHO don't have strong objections (assuming they might because ANC contact numbers are more of an administrative focus than PNC visit numbers)

2. Keep draft events and limited scope. It's more important to that anybody should be able to edit forms in the workflow than tracking the author of each edit. Last (most recent) edit is what's used. If we can still track the original sync'er (ie. author) that's good enough. Possibly do last modified editor, but not important.
Audit trail is not obviously important here. Data overwriting would need to be a user-education thing. Good analogy is a master Word doc on someone's computer vs. offline mode in Google Docs. The Word doc is untenable if changes need to be made whereas at least with Google Docs there's a master file everyone initially shares (which should most of the time be edited by one person at a time). So 2b but without the "originator" restriction.

**Comment by hmakandi** [comment]
A note on the decisions made by the client are:

1. To keep the contact numbers, so we will be proceeding with this change as per issue #293 

2. The workflow changes are not necessary at this point in time, as there will be no multiple actors at this stage of the pilot.
