### ISSUE TITLE
Design Considerations: Navigation Drawer/Bottom Navigation Profile View

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#32]
- [x] Navigation Bar: We need to have a mockup of a navigation bar that has all the registers for this implementation(All Clients/Child/ANC/Maternity/PNC/OPD). For reporting Will it be the same as ZEIR. Could we have a mash of the two to work with?
![Screenshot_1561384226](https://user-images.githubusercontent.com/18394882/60024411-641bfb80-96a0-11e9-8ed1-e36c1781666f.png)
![Screenshot_1561384304](https://user-images.githubusercontent.com/18394882/60024416-68481900-96a0-11e9-8b53-acedede56ca2.png)

- [ ] Bottom menu should have Home, Search, Register, and Me(For site/pop characteristics) across all registers

- [ ] Please share a mockup for all clients with the check in option

- [ ] After the check in option, advise if for now we can select the register to check the person into?

- [ ] Same form can be used to capture the profile of the patient. Advise if we should use the ANC or Child profile view below or another?
![Screenshot_1561389559](https://user-images.githubusercontent.com/18394882/60031002-a0edef80-96ac-11e9-8810-cd575fdbbfd2.png)
![Screenshot_1561389511](https://user-images.githubusercontent.com/18394882/60031006-a2b7b300-96ac-11e9-937e-d5af69847733.png)

- [ ] Reporting considerations. All modules will have reports that are displayed, get aggregated, and submitted to DHIS2. It should allow for editing.
![Screenshot_1561390621](https://user-images.githubusercontent.com/18394882/60032837-0b545f00-96b0-11e9-9945-e50be07d3a1e.png)

**Comment by rowo** [comment]
@hmakandi do we have an All Clients and OPD? I thought the discussion concluded that they would be one and the same for Malawi. I actually like them split apart, but just wanted to make sure.

**Comment by rowo** [comment]
Recent meeting ([notes](https://marvelapp.com/project/4010710/screen/58544951/comments/)) ran long and didn't get to a few questions to be able to finalize this issue:

- Unclear if Advanced Search is going to be a functionality we want to add b/c All Clients lets you search for everyone that's been synced and currently it only exists for Child/ZEIR. Use case description (in notes) doesn't clearly point to needing to add this.
- Service location was mentioned by client but unclear whether it's a requirement for this limited project since it only really exists for ZEIR right now.

**Comment by hmakandi** [comment]
New mockups with All clients and an inline blue register was agreeable.
Advance search was removed in this implementations.
Service locations was agreed to be provided for Malawi.

Closing this item as no further actions are due
