### ISSUE TITLE
OpenSRP and OpenMRS Sync

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#86]
- [x] Load the concepts to OpenMRS

- [x] Ensure OpenSRP data syncs to OpenMRS data

- [ ] M_ZEIR ID[ issue 109](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/109)

- [ ] Birth registration/vaccination event update time precedence[ #110](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/110)

**Comment by bennsimon** [comment]
Sync to OpenMrs is caused by the following issues:

1. `MER_ID` was set as required even though we use `ZEIR_ID` in most of the registers
2. `ZEIR_ID` and other opensrp ids which have hyphens were removed, hence failing the luhn validation
3.  New Encounters have not been created....hence events don't sync

**Comment by hmakandi** [comment]
Made mother's dob made required and confirmed on OpenMRS
